### ISSUE TITLE
triqng/triq doesn't seem to exist anymore/has moved

### ISSUE THREAD

**Issue by PragTob** [safwank/Numerix#6]
Hi there!

Thanks for providing a numbers and statistics library!

```
tobi@speedy:~/github/Numerix(master)$ mix deps.get
* Updating triq (https://github.com/triqng/triq.git)
fatal: could not read Username for 'https://github.com': No such device or address
** (Mix) Command "git --git-dir=.git fetch --force --quiet --progress" failed
```

One of the test dependencies. `mix deps.get --only dev` helps as a workaround`

**Comment by safwank** [comment]
Hi @PragTob, thanks for highlighting the issue. I've been thinking of migrating the tests to either quixir or StreamData, so this is a great excuse to hasten it!

**Comment by safwank** [comment]
Should be fixed in https://github.com/safwank/Numerix/commit/b67a5d7cd6a5a7c76da951e85c25db3d86243787.
